# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'iOSInformation' do
  # Uncomment this line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for iOSInformation
  pod 'Masonry'
  pod 'MJRefresh'
  pod 'hpple'
  pod 'AFNetworking', '~> 3.0'
  pod 'FLAnimatedImage'
  pod 'IDMPhotoBrowser'
  pod 'Realm'
  pod 'FDFullscreenPopGesture'
#  pod 'NYTPhotoViewer', '~> 1.1.0'
end
